config/routes.rb
Rails.application.routes.draw do
# HOME
  root 'home#index'

# SESSIONS
  get "/auth/:provider/callback" => "sessions#create"
  delete '/logout', to: 'sessions#destroy'

  get '/sites/:id/additional-info' => 'sites#edit_additional_info', as: 'add_info'
  patch '/sites/:id' => 'sites#update_additional_info'
  # difficult with route matching??
  
  resources :sites do
    resources :team_members
    resources :gallery_pictures
    resources :testimonials
    resources :treatments
  end

end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  belongs_to :site
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController

  def index
    @team_members = TeamMember.where(site_id: params[:site_id])
    @site = Site.find(params[:site_id])
  end

  def new
    @site = Site.find(params[:site_id])
    @team_member = @site.team_members.new
    # @user = current_user
  end


  def create
    @site = Site.find(params[:site_id])
    @team_member = @site.team_members.new(create_team_member_params[:team_member])
    if(@team_member.save)
      redirect_to site_team_members_path
    else
      render :new
    end

    # each time a member is created save them ALL as JSON?
    # OR ONLY DO IT WHEN LAUNCH SITE?

    @team_members = TeamMember.where(site_id: params[:site_id])
    @team_members_json = []

    @team_members.each do |team_member|
      team_member_json = {
      "name" => team_member.name,
      "image" => team_member.image,
      "email" => team_member.email,
      "phone" => team_member.phone
      }
    @team_members_json << team_member_json
    end

    # File.open("public/#{current_user.id}/#{@site.id}/team_member.json","w") do |f|
    File.open("public/#{current_user.id}-#{@site.id}-team_members.json","w") do |f|
      f.write(@team_members_json.to_json)
    end



  end

  def edit
    @team_member = TeamMember.find(params[:id])
    @site = Site.find(params[:site_id])
    render :new
  end

  def update
    @team_member = TeamMember.find(params[:id])
    @team_member.update(team_member_update_params[:team_member])
    redirect_to site_team_members_path
  end

  def destroy
    @team_member = TeamMember.find(params[:id])
    # @site = Site.find(params[:site_id])
    @team_member.destroy
    redirect_to site_team_members_path
  end

  private
  def create_team_member_params
      params.permit(team_member: [:name, :image, :email, :phone])
  end

  def team_member_update_params
      params.permit(team_member: [:name, :image, :email, :phone])
  end

end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/team_members/index.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <% if current_user %>
    <%= render "shared/submenu"%>
    <h2 class="sub-header">Miembros del equipo</h2>

    <%=link_to "Agregar miembro del equipo", new_site_team_member_path(@site.id), class:"btn btn-primary btn-sm active padded", role:"button"%>
      <div class="table-responsive">
        <table class="table table-striped">
          <tbody>
            <% @team_members.each do |team_member| %>
            <tr>
              <td><%=team_member.name%></td>
              <td><%=link_to "Editar", edit_site_team_member_path(id: team_member.id)%></td>
              <td><%= link_to "Eliminar", site_team_member_path(id: team_member.id), method: :delete%></td>
            </tr>
            <%end%>
          </tbody>
        </table>
      </div>

  <% end %>
</div>

app/views/team_members/new.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <%= render "shared/submenu"%>
  <h2>Agrega a un nuevo miembro de tu equipo aquí:</h2>

  <section class = "form-container">
    <%= bootstrap_form_for([@site, @team_member], layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-8") do |f| %>
      <%= f.text_field :name, label: "Nombre" %>
      <%= f.file_field :image, label: "Foto" %>
      <%= f.text_field :email, label: "Correo Electrónico"%>
      <%= f.text_field :phone, label: "Teléfono"%>
      <%= f.submit "Guardar" %>
    <% end %>
  </section>
</div>