config/routes.rb
Rails.application.routes.draw do
# HOME
  root 'home#index'

# SESSIONS
  get "/auth/:provider/callback" => "sessions#create"
  delete '/logout', to: 'sessions#destroy'

  get '/sites/:id/additional-info' => 'sites#edit_additional_info', as: 'add_info'
  patch '/sites/:id' => 'sites#update_additional_info'
  # difficult with route matching??
  
  resources :sites do
    resources :team_members
    resources :gallery_pictures
    resources :testimonials
    resources :treatments
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if current_user
      @sites = current_user.sites
    end 
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if current_user %>

  <div class="col-sm-12 col-md-12 main">
    <h1 class="page-header">Mis sitios:</h1>

    <div class="row placeholders">


      <% @sites.each do |site| %>
        <div class="col-xs-6 col-sm-3 placeholder">
          <%=link_to image_tag("data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==", :width=>"100", :height=>"100", :class =>"img-responsive"), add_info_path(site.id)%>
          <h4><%=link_to site.title, add_info_path(site.id)%></h4>
          <span class="text-muted"><%= link_to "Eliminar", site_path(site.id), method: :delete, data: {confirm: "¿Estás seguro que deseas eliminar el sitio?"}%></span>
        </div>
      <% end %>

    </div>
    <div class="text-center">
      <%= link_to "Crear un nuevo sitio", new_site_path, class:"btn btn-primary btn-lg active", role:"button"%>
    </div>
</div>
<%else%>
  ¡Tener un sitio web es esencial para el éxito de tu práctica!
  <%= link_to 'Regístrate aquí', '/auth/google' %> para crear un nuevo sitio.
<% end %>