config/routes.rb
Rails.application.routes.draw do
# HOME
  root 'home#index'

# SESSIONS
  get "/auth/:provider/callback" => "sessions#create"
  delete '/logout', to: 'sessions#destroy'

  get '/sites/:id/additional-info' => 'sites#edit_additional_info', as: 'add_info'
  patch '/sites/:id' => 'sites#update_additional_info'
  # difficult with route matching??
  
  resources :sites do
    resources :team_members
    resources :gallery_pictures
    resources :testimonials
    resources :treatments
  end

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  belongs_to :site
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController

    def index
      @testimonials = Testimonial.where(site_id: params[:site_id])
      @site = Site.find(params[:site_id])
    end

    def new
      @site = Site.find(params[:site_id])
      @testimonial = @site.testimonials.new
    end


    def create
      @site = Site.find(params[:site_id])
      @testimonial = @site.testimonials.new(create_testimonial_params[:testimonial])
      if(@testimonial.save)
        redirect_to site_testimonials_path
      else
        render :new
      end
    end

    def edit
      @testimonial = Testimonial.find(params[:id])
      @site = Site.find(params[:site_id])
      render :new
    end

    def update
      @testimonial = Testimonial.find(params[:id])
      @testimonial.update(testimonial_update_params[:testimonial])
      redirect_to site_testimonials_path
    end

    def destroy
      @testimonial = Testimonial.find(params[:id])
      # @site = Site.find(params[:site_id])
      @testimonial.destroy
      redirect_to site_testimonials_path
    end

    private
    def create_testimonial_params
        params.permit(testimonial: [:name, :description, :title])
    end

    def testimonial_update_params
        params.permit(testimonial: [:name, :description, :title])
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/index.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <% if current_user %>
    <%= render "shared/submenu"%>
    <h2 class="sub-header">Comentarios</h2>

    <%=link_to "Agregar nuevo comentario", new_site_testimonial_path(@site.id), class:"btn btn-primary btn-sm active padded", role:"button"%>
    <div class="table-responsive">
      <table class="table table-striped">
        <tbody>
          <% @testimonials.each do |testimonial| %>
          <tr>
            <td><%=testimonial.name%></td>
            <td><%=link_to "Editar", edit_site_testimonial_path(id: testimonial.id)%></td>
            <td><%= link_to "Eliminar", site_testimonial_path(id: testimonial.id), method: :delete%></td>
          </tr>
          <%end%>
        </tbody>
      </table>
    </div>

  <% end %>
</div>

app/views/testimonials/new.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <%= render "shared/submenu"%>
  <h2>Agrega un nuevo comentario sobre tu clínica aquí:</h2>

  <section class = "form-container">
    <%= bootstrap_form_for([@site, @testimonial], layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-8") do |f| %>
    <%= f.text_field :name, label: "Nombre" %>
    <%= f.text_field :title, label: "Título" %>
    <%= f.text_area :description, label: "Comentario" %>

    <%= f.submit "Guardar" %>
    <% end %>
  </section>
</div>