config/routes.rb
Rails.application.routes.draw do
# HOME
  root 'home#index'

# SESSIONS
  get "/auth/:provider/callback" => "sessions#create"
  delete '/logout', to: 'sessions#destroy'

  get '/sites/:id/additional-info' => 'sites#edit_additional_info', as: 'add_info'
  patch '/sites/:id' => 'sites#update_additional_info'
  # difficult with route matching??
  
  resources :sites do
    resources :team_members
    resources :gallery_pictures
    resources :testimonials
    resources :treatments
  end

end

app/models/gallery_picture.rb
class GalleryPicture < ActiveRecord::Base
  belongs_to :site
end

app/models/json_datum.rb
class JsonDatum < ActiveRecord::Base
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :gallery_pictures
  has_many :team_members
  has_many :treatments
  has_many :testimonials
  belongs_to :user
end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  belongs_to :site
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  belongs_to :site
end

app/models/treatment.rb
class Treatment < ActiveRecord::Base
  belongs_to :site
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sites
  
  def self.find_or_create_from_omniauth(auth_hash)
    # Find or create a user
    #user = User.where(uid: auth_hash["uid"]).where(provider: auth_hash["provider"]).first
    user = self.find_by(uid: auth_hash["uid"], provider: auth_hash["provider"])
    # user = //something else here//
    if !user.nil?
    #   return user that was found
      return user
    else
    #   no user found, do something here
      user = User.new
      user.uid = auth_hash["uid"]
      user.provider = auth_hash["provider"]
      user.first_name = auth_hash["info"]["first_name"]
      user.image = auth_hash["info"]["image"]
      user.url = auth_hash["info"]["urls"][user.provider.capitalize] if auth_hash["info"]["urls"]

      if user.save
        return user
      else
        return nil
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if current_user
      @sites = current_user.sites
    end 
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    #accepts OAuth information from Google, finds or creates a User account, and sets user_id in session
    auth_hash = request.env['omniauth.auth']   #request is a variable that you get
    @user = User.find_or_create_from_omniauth(auth_hash)
    # user = User.log_in(params[:xemail], params[:password])
    if @user
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def destroy
    #deletes user_id from session
    session.delete :user_id
    redirect_to root_path
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  def index
    @sites = current_user.sites
  end

  def new
    @site = Site.new
    @user = current_user
  end


  def create
    @site = Site.new(create_site_params[:site])
    if(@site.save)
      current_user.sites << @site
      redirect_to root_path
    else
      render :new
    end
  end
# #####
  def edit
    @site = current_user.sites.find(params[:id])
    render :new
  end

  def update
    @site = current_user.sites.find(params[:id])
    @site.update(site_update_params[:site])
    redirect_to root_path
  end

  def edit_additional_info
    @site = current_user.sites.find(params[:id])
  end

  def update_additional_info
    @site = current_user.sites.find(params[:id])
    @site.update(site_additional_params[:site])
    flash.notice = "Los cambios se guardaron exitosamente."
    redirect_to add_info_path
  end

  def destroy
    @site = current_user.sites.find(params[:id])
    @site.destroy
    redirect_to root_path
  end
#######

  private

  def create_site_params
    params.permit(site: [:title, :description])
  end

  def site_update_params
    params.permit(site: [:title, :description])
  end

  def site_additional_params
    params.permit(site: [:title, :description, :logo, :hero_img, :hero_title, :hero_description, :phone, :emergency, :email, :address,
      :monfri_hours, :sat_hours, :sun_hours, :testimonials_img, :facebook, :twitter, :instagram, :youtube, :skype, :pie])
  end
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController

  def index
    @treatments = Treatment.where(site_id: params[:site_id])
    @site = Site.find(params[:site_id])
  end

  def new
    @site = Site.find(params[:site_id])
    @treatment = @site.treatments.new
  end


  def create
    @site = Site.find(params[:site_id])
    @treatment = @site.treatments.new(create_treatment_params[:treatment])
    if(@treatment.save)
      redirect_to site_treatments_path
    else
      render :new
    end
  end

  def edit
    @treatment = Treatment.find(params[:id])
    @site = Site.find(params[:site_id])
    render :new
  end

  def update
    @treatment = Treatment.find(params[:id])
    @treatment.update(treatment_update_params[:treatment])
    redirect_to site_treatments_path
  end

  def destroy
    @treatment = Treatment.find(params[:id])
    # @site = Site.find(params[:site_id])
    @treatment.destroy
    redirect_to site_treatments_path
  end

  private
  def create_treatment_params
      params.permit(treatment: [:icon, :title, :description])
  end

  def treatment_update_params
      params.permit(treatment: [:icon, :title, :description])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_pictures_helper.rb
module GalleryPicturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odontopaginas</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" href="../../favicon.ico">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>


    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">

  <!-- the main app navbar -->

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Odontopáginas', root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

          <% if current_user %>
            <ul class="nav navbar-nav">
            </ul>

            <ul class="nav navbar-nav pull-right">
              <li><%= link_to ('Hola ' + current_user.first_name + '!'), root_path%></li>
              <li><%= image_tag current_user.image, alt: current_user.first_name %></li>
              <li><%= link_to 'Salir', logout_path, method: :delete %></li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav">
              <!-- link to sites path, galeria -->
            </ul>
            <ul class="nav navbar-nav pull-right">
              <li><%= link_to 'Registrarse', '/auth/google' %></li>
            </ul>
          <% end %>

        </div>
      </div>
    </nav>

  <!-- end of main app navbar -->

  </head>
  <body>

    <div class="container-fluid">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>

  <div class="navbar-fixed-bottom">
  <footer>
    2016 - Odontopaginas.com
  </footer>
  </div
</html>

app/views/shared/_submenu.html.erb
<!-- LEFT MENU -->
<div class="col-sm-3 col-md-2 sidebar">
  <div class="placeholder">
    <%=link_to image_tag("data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==", :width=>"100", :height=>"100", :class =>"img-responsive"), add_info_path(@site.id)%>
    <h3><%= @site.title%></h3>
  </div>
  <ul class="nav nav-sidebar">
    <li class="<%= 'active' if params[:controller] == 'sites' %>"><%= link_to "Información General", add_info_path(@site.id)%></li><span class="sr-only">(current)</span></a></li>
    <li class="<%= 'active' if params[:controller] == 'team_members' %>"><%=link_to "Equipo", site_team_members_path(@site.id)%></li>
    <li class="<%= 'active' if params[:controller] == 'treatments' %>"><%=link_to "Tratamientos", site_treatments_path(@site.id)%></li>
    <li class="<%= 'active' if params[:controller] == 'testimonials' %>"><%=link_to "Comentarios", site_testimonials_path(@site.id)%></li>
    <li class="<%= 'active' if params[:controller] == 'gallery_pictures' %>"><%=link_to "Galería", site_gallery_pictures_path(@site.id)%></li>
    <li><%=link_to "Vista Previa", root_path%></li>
  </ul>
</div>
<!-- END LEFT MENU -->